---
# tasks file for role-lighthouse
- name: Install nginx
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - nginx
- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
- name: Create config for Nginx
  ansible.builtin.template:
    src: template/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Restart-nginx service
  tags: nginx
- name: SYSTEM | Install lighthouse
  include_tasks: lighthouse.yml